name: Terraform + Kubernetes CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Create kind cluster
        run: |
          kind create cluster --name terraform-ci
          kind get kubeconfig --name terraform-ci > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="kubeconfig_path=${KUBECONFIG}"


      - name: Wait for NGINX Pod
        run: |
          kubectl wait --for=condition=ready pod -l app=nginx --timeout=120s

      - name: Validate NGINX HTTP 200
        run: |
          NGINX_POD=$(kubectl get pods -l app=nginx -o jsonpath="{.items[0].metadata.name}")
          kubectl port-forward $NGINX_POD 8080:80 &
          sleep 10
          curl -I http://localhost:8080 | grep "200 OK"

      - name: Wait for MySQL Pod
        run: |
          kubectl wait --for=condition=ready pod -l app=mysql --timeout=180s

      - name: Validate MySQL (Safe Wait + SQL Query)
        run: |
          echo "Waiting for MySQL internal readiness..."

          MYSQL_POD=$(kubectl get pods -l app=mysql -o jsonpath="{.items[0].metadata.name}")

          for i in {1..30}; do
            if kubectl exec $MYSQL_POD -- \
              mysqladmin ping -uroot -prootpassword --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "MySQL not ready yet... retrying ($i/30)"
            sleep 5
          done

          echo "Running SQL validation..."
          kubectl exec $MYSQL_POD -- \
            mysql -uroot -prootpassword -e "SHOW DATABASES;"

      - name: Terraform Destroy
        if: always()
        run: terraform destroy -auto-approve -var="kubeconfig_path=${KUBECONFIG}"
