name: Terraform + Kubernetes CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kind
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/kind

      - name: Create kind cluster
        run: |
          kind create cluster --name terraform-ci
          kind get kubeconfig --name terraform-ci > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="kubeconfig_path=$KUBECONFIG"

      - name: Validate NGINX
        run: |
          kubectl port-forward svc/nginx-service 8080:80 &
          sleep 5
          curl -I http://localhost:8080 | grep "200 OK"

      - name: Validate MySQL
        run: |
          MYSQL_POD=$(kubectl get pods -l app=mysql -o jsonpath="{.items[0].metadata.name}")
          kubectl exec $MYSQL_POD -- \
            mysql -uroot -prootpassword -e "SHOW DATABASES;"

      - name: Terraform Destroy
        if: always()
        run: terraform destroy -auto-approve -var="kubeconfig_path=$KUBECONFIG"
